### ISSUE TITLE
ローカルでのページの確認

### ISSUE THREAD

**Issue by degawa** [Fortran-jp/fortran-jp.org#24]
- pull requestsで修正内容は確認できるが，Webページとしての仕上がりを確認できない
- pull requestsの修正内容をローカルリポジトリにクローンすることはできるが，Webページとして表示するには何が必要か？

### pull requestをローカルリポジトリにコピーする方法
1. ローカルリポジトリを上流と同期する．<br>
1. pull requestで提案された変更を含むコードを確認するには，pull requestを含んだ別のブランチを作成する．これを行うには，個別のpull requestに割り振られた番号を利用する．
`Pull requests`タブからpull requestの一覧を表示し，動作確認したいpull requestを開くと，ブラウザのアドレスバーに番号を含んだURLが表示される．例えば`https://github.com/Fortran-jp/fortran-jp.org/pull/23`のプルリクエストの番号は23である．<br>
1. pull requestの変更を含んだコードを手元のリポジトリの新しいブランチに取り込むには，次のコマンドを実行する．
`git fetch origin pull/23/head:BRANCHNAME` （fortran-jpリポジトリを直接`clone`した場合）
`git fetch upstream pull/23/head:BRANCHNAME` （fortran-jpリポジトリをforkしたリポジトリを`clone`した場合[fortran-jpのリポジトリをupstreamに登録していることが前提]）
ここで，`BRANCHNAME`は自身で適切な名前に置き換える．例えば，`pullreq_23`等，既存のブランチと衝突しにくく，連想しやすい名前がよい．
`git fetch origin pull/23/head:pullreq_23`を実行しても，見かけ上は何も変更されないが，Git Graph等でリポジトリのコミット履歴を見ると，新しいブランチが作られていることを確認できる．<br>
1. `git switch pullreq_23`を実行すると，pull requestの変更を含んだコードがチェックアウトされ，ソースコードを確認したり，コンパイルしたりできるようになる．

**Comment by osada-yum** [comment]
https://docs.github.com/ja/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll
を参考にして, 
- リポジトリをクローン.
  `git clone [...]`
- ローカルのファイルでGemfileを(強制的に)生成.
  `cd fortran-jp.org`
  ` jekyll new --skip-bundle --force .` 
- Gemfileの中を, https://pages.github.com/versions/ を参考に変更.
 ```
"jekyll", "~> 3.9.0"
"github-pages", "~> 225"
"jekyll-feed", "~> 0.15.1"
```
- `bundle install` をする.
- _config.yml が(jekyll newで)置き換わってしまっているので戻す.
  `git restore _config.yml`
- ページを確認, localhost:4000 にアクセス.
  `bundle exec jekyll serve`

でできました.
Ubuntu20.04でruby-2.7.0, gem-3.1.2です.
jekyllとbundlerは https://jekyllrb.com/docs/installation/ のUbuntuの手順でインストールしました.

**Comment by degawa** [comment]
# Ubuntu
## 必須ソフトウェア
- Ruby 2.5.0 or higher
- RubyGems
- gcc
- make

### 必須ソフトウェアのインストール
```
sudo apt-get install ruby-full build-essential zlib1g-dev
```

### `.bashrc`への設定の追記
下記（コメントは必須ではない）を`~/.bashrc`に追記する．
```bash
# Install Ruby Gems to ~/gems
export GEM_HOME="$HOME/gems"
export PATH="$HOME/gems/bin:$PATH"
```

追記した`.bashrc`を読み込む
```
source ~/.bashrc
```

### JekyllとBundlerのインストール
下記コマンドを実行する．
```
gem install jekyll bundler
```

## ローカルでのページ生成とブラウザでのアクセス
1. gemfileの生成
リポジトリをクローン氏，gemfileを生成する．
```
git clone https://github.com/Fortran-jp/fortran-jp.org.git
cd fortran-jp.org
jekyll new --skip-bundle --force .
```
2. Gemfileを編集
```diff
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
- gem "jekyll", "~> 4.2.2"
+ gem "jekyll", "~> 3.9.0"
# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.5"
# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
- # gem "github-pages", group: :jekyll_plugins
+ gem "github-pages", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
-  gem "jekyll-feed", "~> 0.12"
+  gem "jekyll-feed", "~> 0.15.1"
end
``` 
3. ページ生成
```
bundle install
```
4.  `_config.yml`を元に戻す
`jekyll new ...`を実行した際に`_config.yml`が置き換えられているので，gitを利用して元に戻す
```
git restore _config.yml
```
5. jekyllを起動
下記コマンドを実行し，jekyllを起動する．
```
bundle exec jekyll serve
```
6. ブラウザでアクセス
ブラウザで`http://localost:4000`にアクセスすると，ページが表示される．

# Windows
## WSLでjekyllを起動し，Windowsからアクセスする場合
WSL2では，WSL2の上に建てたサーバーに，Windowsからアクセスできるように設定されている．WSL上のUbuntuで，前節（Ubuntu）と同じ設定を行い，Windowsのブラウザから`http://localost:4000`にアクセスすればよい．

アクセスできない場合は，`C:\Users\ユーザ名\.wslconfig`に`localhostForwarding=False`が書かれていないかを確認する．
書かれている場合は，`localhostForwarding=True`に書き換えて再起動する．
